[package]
name = "utiscript"
version = "0.1.0"
edition = "2024"

[dependencies]
toml = "0.8.2"
clap = { version = "4.0", features = ["derive"] }
termcolor = "1.1"

[[bin]]
name = "clay"
path = "src/main.rs"